### ISSUE TITLE
extra Login alert is redundant

### ISSUE THREAD

**Issue by mt-empty** [ahm-monash/evergreen#283]
![image](https://user-images.githubusercontent.com/59728838/199664486-2a54ebc4-761e-4686-8985-f738283ecb5e.png)

**Comment by Akshith-Patil** [comment]
Hey Matti, its actually supposed to be a tick icon below the 'Success!' text, see the attached image below. For some reason it's showing the name of the image, I will look into it. 
![image](https://user-images.githubusercontent.com/81655881/199667834-ff842377-1769-4c12-97f3-197a8967ca26.png)
