### ISSUE TITLE
Mobile View Light Status Pop Up Issue

### ISSUE THREAD

**Issue by alexdelicato** [ahm-monash/evergreen#307]
When selecting the information button on the second slide in the summary section in mobile view it comes up in the first slide and there is no way of removing it.
![image](https://user-images.githubusercontent.com/81656054/201447323-ba10e750-d58c-41a7-b214-517635289817.png)

![image](https://user-images.githubusercontent.com/81656054/201447289-d1a63ac0-e9e9-41c8-9501-716f5f7f5f6a.png)

**Comment by Akshith-Patil** [comment]
Maybe we can delete the light status legend for mobile view. Since the help guide is easily reachable from the bottom right on mobiles.
